---

- name: creazione file di testo
  hosts: localhost
  connection: local

  tasks:

    - name: crea cartella
      ansible.builtin.file:
        path: /home/playbook
        state: directory
        mode: "700"

    - name: crea file
      ansible.builtin.copy: 
        content: "buon appetito, da fabio tozzi"
        dest: /home/playbook/file.txt

    - name: salva contenuto del file 
      ansible.builtin.command: 
        cmd: cat  /home/playbook/file.txt
      register: messaggio

    - name: stampa messaggio
      ansible.builtin.debug:
        msg: "{{ messaggio.stdout_lines }}"




